### PR TITLE
SC2164: Make SC2164 apply to `pushd` and `popd`

### LINKED ISSUE #863: `pushd` and `popd` should be treated like `cd`
#### For bugs
- Rule Id (if any, e.g. SC1000): 
- My shellcheck version (`shellcheck --version` or "online"): 0.4.6
- [X] I tried on shellcheck.net and verified that this is still a problem on the latest commit
- [ ] It's not reproducible on shellcheck.net, but I think that's because it's an OS, configuration or encoding issue

#### For new checks and feature suggestions
- [X] shellcheck.net (i.e. the latest commit) currently gives no useful warnings about this
- [X] I searched through https://github.com/koalaman/shellcheck/issues and didn't find anything related

#### Here's a snippet or screenshot that shows the problem:

```sh
#!/bin/bash
cd /foo
pushd /bar
popd
```

#### Here's what shellcheck currently says:

```
In demo.sh line 2:
cd /foo
^-- SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
```

#### Here's what I wanted or expected to see:

```
In demo.sh line 2:
cd /foo
^-- SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.


In demo.sh line 3:
pushd /bar
^-- SC2164: Use 'pushd ... || exit' or 'pushd ... || return' in case pushd fails.


In demo.sh line 4:
popd
^-- SC2164: Use 'popd || exit' or 'popd || return' in case popd fails.
```
`pushd` and `popd` have exactly the same failure cases as `cd`; SC2164 should apply to them as well.

### PR DESCRIPTION
**Pull request by mrshu**
* Since `pushd` and `popd` have the same failure cases, make the check
  for SC2164 apply to them as well.

* This commit also refactors the code a bit as `hasSetE` is now used in
  multiple places.

* Fixes #863.

Signed-off-by: mr.Shu <mr@shu.io>

### CODE REVIEW

File: ShellCheck/Analytics.hs [hunk 1]
```diff
@@ -2548,7 +2550,47 @@ checkUncheckedCd params root =
                 warn (getId t) 2164 "Use 'cd ... || exit' or 'cd ... || return' in case cd fails."
```
Comment (koalaman) [inline ShellCheck/Analytics.hs]: Neat! How about adding pushd/popd to the checkUncheckedCd method to avoid reiterating the tree several times. Maybe something like 

    checkElement t@T_SimpleCommand {} =
      when (name `elem` ["cd", "pushd", "popd"])
          ...  $ do
          warn (getId t) 2164 $ "Use '" ++ name ++ " ... || exit'  ...."
      where
        name = fromMaybe "" $ getCommandName t
        isSafeDir t = case oversimplify t of 
              [_, ".."] -> True; 
              _ -> False

**Comment by mrshu** [comment]
@koalaman thanks for your suggestion -- it was indeed a very good one! Also many thanks for putting `hasSetE` into the lib -- I believe that is where it should indeed be placed.

Please let me know what you think!

File: ShellCheck/Analytics.hs [hunk 2]
```diff
@@ -2463,26 +2463,48 @@ checkReadWithoutR _ t@T_SimpleCommand {} | t `isUnqualifiedCommand` "read" =
...
+prop_checkUncheckedPopd1 = verifyTree checkUncheckedCdPushdPopd "popd; rm -r foo"
+prop_checkUncheckedPopd2 = verifyNotTree checkUncheckedCdPushdPopd "popd || exit; rm -r foo"
+prop_checkUncheckedPopd3 = verifyNotTree checkUncheckedCdPushdPopd "set -e; popd; rm -r foo"
+prop_checkUncheckedPopd4 = verifyNotTree checkUncheckedCdPushdPopd "if popd; then rm foo; fi"
+prop_checkUncheckedPopd5 = verifyTree checkUncheckedCdPushdPopd "if true; then popd; fi"
+prop_checkUncheckedPopd6 = verifyTree checkUncheckedCdPushdPopd "popd"
+prop_checkUncheckedPopd7 = verifyNotTree checkUncheckedCdPushdPopd "#!/bin/bash -e\npopd\nrm bar"
+prop_checkUncheckedPopd8 = verifyNotTree checkUncheckedCdPushdPopd "set -o errexit; popd; rm bar"
+
+checkUncheckedCdPushdPopd params root =
```
Comment (mrshu) [inline ShellCheck/Analytics.hs]: @koalaman I am not sure if you agree with the change of the name of the function, but it did feel appropriate to me.

File: ShellCheck/Analytics.hs [hunk 3]
```diff
@@ -2463,26 +2463,48 @@ checkReadWithoutR _ t@T_SimpleCommand {} | t `isUnqualifiedCommand` "read" =
...
+    if hasSetE params then
+        []
     else execWriter $ doAnalysis checkElement root
   where
     checkElement t@T_SimpleCommand {} =
-        when(t `isUnqualifiedCommand` "cd"
-            && not (isCdDotDot t)
+        when(name t `elem` ["cd", "pushd", "popd"]
+            && not (isSafeDir t)
+            && not (name t == "pushd" && ("n" `elem` map snd (getAllFlags t)))
```
Comment (mrshu) [inline ShellCheck/Analytics.hs]: @koalaman I do not really like this line, but sadly, this is the only way I managed to get `pushd -n` to be skipped.

If you can think of a better way, please let me know.

**Comment by koalaman** [comment]
Thanks!
